### ISSUE TITLE
画面一覧・レイアウト設計

### ISSUE THREAD

**Issue by renny-m** [renny-m/wealth_sync#6]
# 概要
フロントエンドを実装するための画面イメージを作成する
まずは要件を満たす最低ラインのレイアウトを作成し、細かいデザインは後から改善する

# TODO
- [x] figmaプロジェクト作成
- [x] 画面設計用の大枠準備
- [x] 参考画面としてspreadsheetの画面キャプチャ貼り付け
- [ ] 画面遷移図（概要）作成
- [ ] 各画面レイアウトのモック作成 [※参考](https://kazulog.fun/dev/chatgpt-figma-html-to-design/)
- [ ] レイアウトの調整 ※細かいデザインにこだわりすぎず、一旦は画面として要件を実現できる最低ラインで進める
- [ ] wikiかREADMEにfigmaのURL転記する

# Figma
https://www.figma.com/design/QmpYcOUD65JfsQ0hwMMoRH/wealth-sync?node-id=0-1&t=69llImv9sM4cFreD-1

# 備考

**Comment by renny-m** [comment]
Chat GPTでそれっぽいモックは作れそう 
何度かやりとりして叩き台を作ってから、html to figmaのプラグインで編集可能なレイアウトイメージを作る  
→figmaでレイアウト完成したら、figma to htmlのプラグインでHTML化して、Chat GPTでReactのコードに書き換える

### Chat GPTから1回のやり取りで出力されたHTMLイメージ
<img width="637" alt="image" src="https://github.com/user-attachments/assets/3ee2bb49-225c-4845-962c-c918344ca6b4">

### Chat GPTに入力したプロンプト
```
次の画面構成の案を、HTMLで出力してください。
Bootstrapを利用し、デザインを整えてください。

# 個人資産を管理するためのサマリ画面
## 積立額（表形式で項目を縦に並べる）
- 実績
- 目標
- 実績差

##ポートフォリオ状況
- 二重のドーナツグラフで、外円が実績、内円が目標
- 表形式で、縦に項目、横に割合（目標、実績、差分）と金額（目標、実績、追加購入要否）

##資産推移チャート
- 縦軸が金額で、横軸が時間
- 目標を薄い色で、実績を濃い色で重ねて表現
```

### html
```html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>個人資産管理サマリ画面</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
  <div class="container my-5">
    <!-- Header -->
    <h1 class="text-center mb-5">個人資産管理サマリ</h1>

    <!-- 積立額セクション -->
    <section class="mb-5">
      <h2 class="mb-3">積立額</h2>
      <table class="table table-bordered">
        <thead class="thead-light">
          <tr>
            <th>項目</th>
            <th>金額</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>実績</td>
            <td>¥100,000</td>
          </tr>
          <tr>
            <td>目標</td>
            <td>¥120,000</td>
          </tr>
          <tr>
            <td>実績差</td>
            <td>¥-20,000</td>
          </tr>
        </tbody>
      </table>
    </section>

    <!-- ポートフォリオ状況セクション -->
    <section class="mb-5">
      <h2 class="mb-3">ポートフォリオ状況</h2>
      <div class="row">
        <!-- ドーナツグラフ -->
        <div class="col-md-6">
          <canvas id="portfolioChart"></canvas>
        </div>
        
        <!-- ポートフォリオ表 -->
        <div class="col-md-6">
          <table class="table table-bordered">
            <thead class="thead-light">
              <tr>
                <th>項目</th>
                <th>目標割合</th>
                <th>実績割合</th>
                <th>差分</th>
                <th>目標金額</th>
                <th>実績金額</th>
                <th>追加購入要否</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>株式</td>
                <td>50%</td>
                <td>45%</td>
                <td>-5%</td>
                <td>¥500,000</td>
                <td>¥450,000</td>
                <td>必要</td>
              </tr>
              <tr>
                <td>債券</td>
                <td>30%</td>
                <td>35%</td>
                <td>+5%</td>
                <td>¥300,000</td>
                <td>¥350,000</td>
                <td>不要</td>
              </tr>
              <!-- 他の資産クラスも追加可能 -->
            </tbody>
          </table>
        </div>
      </div>
    </section>

    <!-- 資産推移チャートセクション -->
    <section>
      <h2 class="mb-3">資産推移チャート</h2>
      <canvas id="assetChart"></canvas>
    </section>
  </div>

  <!-- Chart.jsスクリプト -->
  <script>
    // ポートフォリオのドーナツグラフ設定
    var ctx = document.getElementById('portfolioChart').getContext('2d');
    var portfolioChart = new Chart(ctx, {
      type: 'doughnut',
      data: {
        labels: ['実績', '目標'],
        datasets: [
          {
            label: '実績',
            data: [45, 35, 20], // 仮のデータ
            backgroundColor: ['#4e73df', '#36b9cc', '#1cc88a']
          },
          {
            label: '目標',
            data: [50, 30, 20], // 仮のデータ
            backgroundColor: ['#f6c23e', '#e74a3b', '#858796']
          }
        ]
      },
      options: {
        responsive: true
      }
    });

    // 資産推移チャート設定
    var ctx2 = document.getElementById('assetChart').getContext('2d');
    var assetChart = new Chart(ctx2, {
      type: 'line',
      data: {
        labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'], // 仮のデータ
        datasets: [
          {
            label: '目標',
            data: [100, 150, 200, 250, 300, 350],
            borderColor: 'rgba(78, 115, 223, 0.2)',
            backgroundColor: 'rgba(78, 115, 223, 0.2)',
            fill: true
          },
          {
            label: '実績',
            data: [90, 130, 210, 230, 320, 340],
            borderColor: 'rgba(28, 200, 138, 1)',
            backgroundColor: 'rgba(28, 200, 138, 0.2)',
            fill: true
          }
        ]
      },
      options: {
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero: true
            }
          }]
        },
        responsive: true
      }
    });
  </script>
</body>
</html>

```
